name: API Test Patch Suite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-api-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Robot Framework Tests For Patch
        run: robot -d results tests/patch_object_test.robot

      - name: Upload Test Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: robot-results
          path: results/
